export const LOGIN_IN = 'LOGIN_IN';
export const REGISTER = 'REGISTER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_USER = 'AUTH_USER';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const SINGED_OUT = 'SINGED_OUT';

export const CREATE_JOURNEY = 'CREATE_JOURNEY';
export const GET_JOURNEY_SUCCESS = 'GET_JOURNEY_SUCCESS';
export const SAVE_JOURNEY_SUCCESS = 'SAVE_JOURNEY_SUCCESS';
export const GET_JOURNEYS_SUCCESS = 'GET_JOURNEYS_SUCCESS';

export const SAVE_ENTRY_SUCCESS = 'SAVE_ENTRY_SUCCESS';
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS';
